services:
  tkx-hercules:
    image: tkx-hercules:tk5-latest
    platform: ${PLATFORM:-linux/amd64}
    container_name: tkx-hercules-tk5
    ports:
      - "3270:3270"
      - "8038:8038"
    volumes:
      - tk5-tk5res:/tk5-/tk5res
      - tk5-tk5cat:/tk5-/tk5cat
      - tk5-tk5dlb:/tk5-/tk5dlb
      - tk5-tk5001:/tk5-/tk5001
      - tk5-tk5002:/tk5-/tk5002
      - tk5-tso001:/tk5-/tso001
      - tk5-tso002:/tk5-/tso002
      - tk5-tso003:/tk5-/tso003
      - tk5-work01:/tk5-/work01
      - tk5-work02:/tk5-/work02
      - tk5-work03:/tk5-/work03
      - tk5-work04:/tk5-/work04
      - tk5-int001:/tk5-/int001
      - tk5-page00:/tk5-/page00
      - tk5-spool0:/tk5-/spool0
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'
        reservations:
          memory: 1G
          cpus: '1.0'
    environment:
      - TZ=UTC
      - HERCULES_VERSION=4.60
      - MVS_VERSION=3.8j-tk5
    labels:
      - "com.skunklabz.description=MVS 3.8j Turnkey 5- System on Hercules Mainframe Emulator"
      - "com.skunklabz.version=1.2.0"
      - "com.skunklabz.mvs-version=tk5"

volumes:
  tk5-tk5res:
    driver: local
  tk5-tk5cat:
    driver: local
  tk5-tk5dlb:
    driver: local
  tk5-tk5001:
    driver: local
  tk5-tk5002:
    driver: local
  tk5-tso001:
    driver: local
  tk5-tso002:
    driver: local
  tk5-tso003:
    driver: local
  tk5-work01:
    driver: local
  tk5-work02:
    driver: local
  tk5-work03:
    driver: local
  tk5-work04:
    driver: local
  tk5-int001:
    driver: local
  tk5-page00:
    driver: local
  tk5-spool0:
    driver: local 