name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: tk4-hercules:test
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
    
    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
    
    - name: Run validation tests
      run: |
        chmod +x scripts/validation/*.sh
        ./scripts/validation/quick-validate.sh
    
    - name: Check documentation
      run: |
        # Check if all required documentation files exist
        test -f README.md
        test -f CONTRIBUTING.md
        test -f CHANGELOG.md
        test -f LICENSE
        test -f SECURITY.md
        test -f CODE_OF_CONDUCT.md
        test -f docs/LEARNING_GUIDE.md
        test -f docs/TESTING.md
    
    - name: Check project structure
      run: |
        # Verify directory structure
        test -d scripts/build
        test -d scripts/test
        test -d scripts/validation
        test -d docs
        test -d examples
        test -d .github/ISSUE_TEMPLATE
        test -d .github/PULL_REQUEST_TEMPLATE
        test -d .github/workflows

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install shellcheck
      run: |
        sudo apt-get update
        sudo apt-get install -y shellcheck
    
    - name: Run shellcheck
      run: |
        shellcheck scripts/**/*.sh || true
    
    - name: Check Makefile
      run: |
        make help
    
    - name: Validate YAML files
      run: |
        # Check docker-compose.yml
        docker-compose config
        
        # Check GitHub workflow files
        for file in .github/workflows/*.yml; do
          echo "Validating $file"
          # Basic YAML syntax check
          python3 -c "import yaml; yaml.safe_load(open('$file'))"
        done 