name: Release

on:
  push:
    branches: [ main ]
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version bump type'
        required: true
        default: 'patch'
        type: choice
        options:
        - patch
        - minor
        - major

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Get current version
      id: version
      run: |
        CURRENT_VERSION=$(cat VERSION | tr -d ' ')
        echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
        echo "Current version: $CURRENT_VERSION"
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push to GitHub Container Registry
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ghcr.io/skunklabz/tk4-hercules:latest
          ghcr.io/skunklabz/tk4-hercules:${{ steps.version.outputs.current_version }}
          ghcr.io/skunklabz/tk4-hercules:main
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Create Git tag
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git tag -a "v${{ steps.version.outputs.current_version }}" -m "Release v${{ steps.version.outputs.current_version }}"
        git push origin "v${{ steps.version.outputs.current_version }}"
    
    - name: Create Release Notes
      id: release_notes
      run: |
        # Extract changes from CHANGELOG.md for the current version
        CURRENT_VERSION="${{ steps.version.outputs.current_version }}"
        RELEASE_NOTES=$(awk "/## \[$CURRENT_VERSION\]/,/## \[/" CHANGELOG.md | head -n -1 | tail -n +2)
        echo "release_notes<<EOF" >> $GITHUB_OUTPUT
        echo "$RELEASE_NOTES" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
    
    - name: Create GitHub Release
      if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.version.outputs.current_version }}
        release_name: Release v${{ steps.version.outputs.current_version }}
        body: ${{ steps.release_notes.outputs.release_notes }}
        draft: false
        prerelease: false
    
    - name: Run post-release tests
      run: |
        echo "Running post-release validation..."
        ./scripts/validation/quick-validate.sh
        
        echo "✅ Release v${{ steps.version.outputs.current_version }} created successfully!"
        echo "🔗 Release URL: https://github.com/${{ github.repository }}/releases/tag/v${{ steps.version.outputs.current_version }}"
        echo "🐳 Docker Image: ghcr.io/skunklabz/tk4-hercules:${{ steps.version.outputs.current_version }}" 